LLNL/ATS

ats/ats, ats/ats3, ats/src/ats/bin/_ats.py, ats/src/ats/bin/_ats3.py, ats/src/ats/bin/atslite1.py, ats/src/ats/bin/atslite3.py, ats/src/ats/configuration.py, ats/src/ats/management.py, ats/src/atsMachines/lsf_asq.py, ats/test/HelloATS/ats_hello, ats/test/HelloGPU/READ.ME, ats/test/HelloGPU/test.ats
Remove jsrun_nn / nn option on blueos.  This was a command
line option to over-ride or set the number of nodes for each
test. This option is not needed, and led to confusion.
If nn (number of nodes) is not specified on an individual
test basis when run with jsrun, it will be left unset
if np (number of mpi ranks) is < 40.  This will allow
jsrun to run concurrent jobs across the nodes in the
allocation.   If a test uses >40 mpi ranks, then
nn will be set as necessary to get enough nodes for the
job.  In this case, as the job will span multiple nodes,
the test will be given exclusive access to the resource
nodes via a resource set file.
Side Note: If a user wants to schedule jobs > 40 mpi ranks
which span multiple nodes and do *not* use lsf resouce sets
they should run ATS with the 'lrun' …
=> v7.0.1:  Update LSF JSRUN options

ats/test/HelloATS/ats_check_log.py, ats/test/HelloATS/create_test_ats.py
Test scripts **ats_check_log.py** and **create_test_ats.py** in ats/test/HelloATS are simple enough to upgrade to Python 3 without effecting the user's workflow or any dependencies in other files.
=> upgrade test scripts to Python 3

ats/src/ats/machines.py
Fixing a busted print function that has an extra parenthesis.
=> removed extra closing parenthesis

ats/src/ats/executables.py
During my earlier updates I moved an import statement from an __init__ call to the top of the module. This should have been left alone as the odd location of the import was intentional. Returning the import to the __init__ call is needed, as it is a workaround for a circular dependency. This should eventually be addressed.
=> return import statement to original location

ats/src/ats/machines.py
numNodes is being set in most of the modules in the "atsMachines" directory but is also referenced in some cases before anything from that directory is encountered.
=> default "machine" is missing numNodes

ats/setup.py, ats/tox.ini
With this update, ATS can be built via "tox" or locally with "pip" via "python2 -m pip install --user <path to setup.py>".
Tox creates a virtualenv with a python executable and all the built ATS libraries.
pip installs "ats" and "atsMachines" to your python's site packages.
=> temp fix for building ATS

ats/src/ats/attributedict.py
Lots of ATS files import "atsut.py" which then imports "attributedict.py".
Upgrading most of ATS to python 3 relies on "attributedict.py" being able to run in python 3.
=> update attributedict.py to run with py2 and py3

ats/src/ats/configuration.py, ats/src/ats/management.py, ats/src/atsMachines/slurmProcessorScheduled.py
Update slurm module so it knows
what slurm version is being used. This
is needed due to differences in how
slurm behaves with the update by SchedMD.
The new slurm is on one machine for testing,
other machines have the older slurm.
Fix print statement.  A '%' character
had been lost in the conversion of print
statements to be python 3 compatible.
Remove use of --share when constructing
srun line.  This option is deprecated
and is not supported in current slurm.
Added --unbuffered option at the request
of ATS user.  If specified, will add
-unbuffered to the srun line.  The user
wants to see if this helps them better
view the output from a run.  This is off
by default.
Change miscellaneous use of "-v" when
constructiong the srun line to use
--comment="xxx".  These options can
not be blank, …
=> Slurm version aware and other fixes.

ats/src/ats/bin/atslite1.py, test/HelloATS/ats_hello
ats_hello had baked in assumptions that the system python had ATS installed in its site-packages directory.
=> update ats_hello ats path discovery

ats/src/ats/attributedict.py, ats/src/ats/management.py
While not 100% identical to the 6.x version
of the code, this is update makes the created
atsr.py files, which projects rely upon,
to be much closer to the 6.x version.
This should fix issues reported by a user.
=> Change prints to atsr.py.

ats/src/ats/attributedict.py, ats/src/ats/management.py
While not 100% identical to the 6.x version
of the code, this is update makes the created
atsr.py files, which projects rely upon,
to be much closer to the 6.x version.
This should fix issues reported by a user.
=> Change print to atsr.py (main branch)

ats/tests.py
ATS tests were being scheduled out of order due to how two AtsTest instances were being compared.
[Line 644 in ats/management.py](https://github.com/LLNL/ATS/blob/main/ats/management.py#L644) was erroneously checking for tests not in a list based on the test's "totalPriority" attribute. Two tests with the same "totalPriority" would be considered equivalent. Unlike "totalPriority", a test's "serialNumber" attribute is unique and should have been referenced from the beginning.
ATS instructs some tests to wait until a list of other tests have completed before beginning. This list of dependent tests was incomplete and this update fixes this sneaky problem.
=> fix faulty AtsTest comparisons

ats/configuration.py, ats/schedulers.py
Make use of seemingly unused command line option to toggle logging to `atss.log` file.
[Logging to atss.log consumes large amounts of disk space](https://github.com/LLNL/ATS/issues/70) for some projects. This PR aims to provide an opt-out option for projects not interested in this log.
=> DRAFT: repurpose unused option to toggle atss logging

ats/tests.py
Fix syntax error in test options dictionary.
=> make "options" dictionary keys strings

.gitlab-ci.yml, .gitlab/kripke.yml, .gitlab/runners.yml, test/Kripke/README.txt, test/Kripke/ats_check_log.py, test/Kripke/create_test_ats.py, test/Kripke/postrun.py, test/Kripke/prerun.py
Test setup for Kripke testing needed updating and some bugfixes.
- `create_test_ats.py` was trying to import from an external ATS related repository. The external code has been brought into this repo.
- Some print statements have been updated from Python 2.7 format to Python 3 format.
- Attempted to make the code more readable in general.
=> update kripke test, remove external dependencies

ats/bin/atsformat.py, pyproject.toml, setup.cfg
Introducing the `atsformat` command. `atsformat` uses `black` and `isort` to format python files. One initial setback with `black` was its insistence on converting `#ATS:` to `# ATS:` that breaks the code. So `atsformat` lets `black` do this and later reverts `# ATS:` back to `#ATS:` - same for `#BATS:`.
By default, `black` and `isort` are not installed but developers can include these during the ATS installation \
by adding `"[dev]"` like this: `pip install <path to ATS>"[dev]"`
=> add black and isort formatters

ats/atsMachines/fluxScheduled.py, ats/bin/atsflux.py, setup.cfg
Per our discussion today with @dawson6, @davidbloss, and @jameshcorbett, this PR is opened to test the compatibility of a work-in-progress Flux executor and monitor the progress of expanding ATS compatibility for Flux.
Currently, the Flux executor has option compatibility for:
- number of cores
- number of nodes
- exclusivity within an allocation
- verbose output of Flux key value store
To test this on Ruby (or another slurm-runnning LC cluster), install ATS in a virtual environment and request an allocation from slurm:
```salloc -N 3 -p pdebug -A cbronze -t 60```
And then start a flux instance using `srun`:
```srun -N 3 --pty flux start```
=> flux: add compatibility for Flux in the ATS codebase

.gitlab-ci.yml
Problem: Current GitLab CI/CD tests do not test the  binary.
Solution: Add testing for ATS's Flux code.
This should work under @davidbloss's credentials on Quartz, but I saw that @dawson6 you have a different bank, so if it's running under your account I may need to make a slight change. Also, when I tested in my GitLab fork the Kripke tests failed, but I assumed that didn't have anything to do with this commit.
=> testsuite: add flux integration testing

ats/management.py
PR to address the issue in Discussion #101.  This temporarily reverts to the previous exec(test) and exec(compile( test )) mechanisms for ingesting the tests defined in the ats files.
=> Temporarily revert custom ast parser to old exec machinery

ats/configuration.py, docs/source/ats.rst
This PR enables finding machines installed using setuptools' [entry points plugin](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#entry-points-for-plugins) mechanism: 
Sample toml file in a project with these machines (note project/package name is a dummy and not real):
``` toml
[project]
name = "myats"
version = "0.0.1"
description = "MyATS Wrapper"
dependencies = [
"ats",
]
requires-python = ">=3.8"
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[tool.setuptools.packages.find]
where = ["."]
include = ["myats"]
[project.scripts]
myats = "myats.myats:main"  # install console script to launch myats wrapper/driver
[project.entry-points."ats.machines"]
my_slurm_proc_sched = …
```
=> Machines as plugins

ats/atsMachines/lsf_asq.py, ats/configuration.py
Adds options that are similar to the existing jsrun_np and lsrun_np options, but with additional logic to only override the np set for tests if the np is larger than the number provided to these options. This way tests that are meant to run on less processors than specified aren't moved to higher counts.t
This PR will close: https://github.com/LLNL/ATS/issues/94
=> Adding jsrun_np_max option

ats/atsMachines/fluxScheduled.py, ats/tools/atsflux.py
This PR removes flux mini in favor of flux alloc and flux run. This avoids the warning we are currently seeing and alleviates a potential future problem.
This PR closes: https://github.com/LLNL/ATS/issues/117
=> Removing flux mini as it is deprecated

ats/__main__.py, ats/tools/atsflux.py
This PR is a quick bug fix to add a missing equal for the return in atsflux.py. Also removes a semicolon not needed in python.
Added a comment to explain our return from main, to hopefully reduce confusion for other collaborators.
=> Adding missed "equals"

ats/atsMachines/fluxScheduled.py
This PR adds both gpu options available in Flux to ATS as options that can be used when writing an ATS deck, and a bit of error checking to gpus-per-node.
=> Adding GPU options to ATS using Flux

ats/atsMachines/lsf_asq.py, ats/configuration.py
This PR adds documentation and a message when lrun_np_max or jsrun_np_max are used to indicated that they are deprecated. As well as adding a third option, that does the same as the previous two, but will be used in the future to make options between different systems similar.
=> BlueOS option update

RELEASE_NOTES.md
Adds note about BlueOS option changes to release notes and two small format changes.
=> BlueOS option in RELEASE_NOTES

ats/schedulers.py
The priority calculation can be improved if the tests are already sorted by priority, however because of the global module initializations in prioritize(), it cannot be overridden without overridding all methods that reference machine or configuration.
Splitting the priority calculation into a separate method allows it to be overridden easily.
=> Move priority calculation to separate method

ats/atsMachines/fluxScheduled.py, ats/atsMachines/lsf_asq.py, ats/atsMachines/slurmProcessorScheduled.py, ats/configuration.py, ats/machines.py, ats/schedulers.py
This PR adds two options: `--removeStartNote` and `--removeEndNote`
removeStartNote: removes the logStart() call from step(). This gets rid of the "Start" message automatically printed by ATS
removeEndNote: removes the noteEnd() call from testEnded(). This gets rid of the "Stop" message automatically printed by ATS
Additionally, this PR adds a message printed at the end of tests when they are run using flux, to be consistent with the other schedulers.
=> Adding options to reduce prints

ats/atsMachines/fluxScheduled.py, docs/source/ats.rst
This PR adds an option, that works under the Flux scheduler, to allow users to run tests on the same node. It is a per-test option where a string is specified and tests with the same string will be run on the same node. Setting this option will limit the number of nodes you can use for the test to one (-N1) and the number of cores to the maximum on the node (-nMAX), if the user requests more cores than on the node, otherwise -n stays the same.
This PR will close: https://github.com/LLNL/ATS/issues/103
Note: while this is an option working under Flux, we do have Flux working under slrum.
This PR also adds documentation for two previously added command line options: removeStartNote and removeEndNote.
=> Same node option

ats/atsMachines/fluxScheduled.py
This PR is a minor change to have the warning messages from the same_node option to be printed out to the console as well as logged.
=> Warning messages to console

ats/machines.py
This PR addresses the problem that we were seeing with tests, run using Flux, stating that they failed even though it was a time out. Now we check if we are running on a Flux machine and check for the return code from flux and determine that there was a timeout.
There's also a debugging print that I updated to work with python3, but left in because it was there before.
Closes: https://github.com/LLNL/ATS/issues/116
=> Flux timeouts

.readthedocs.yml
The RTD build is currently failing with this error:
```
Error
Config validation error in build.os. Value build not found.
```
=> Fix RTD build

ats/atsMachines/docker.py
Adds a (hopefully) general machine to the list of ATS machines.
=> Add a general ATS machine called docker

ats/atsMachines/fluxScheduled.py, ats/configuration.py, ats/util/generic_utils.py
This PR adds logic to find the flux python library on flux machines.
=> Find flux python

ats/machines.py, ats/reportutils.py, ats/tests.py
Update opens with errors='ignore' in attempt to stop the python coding in ATS from dying when it reads output generated by applications which are not utf-8 valid.  This can happen when applications print garbage output -- but when this happens the python in ATS breaks and the testing breaks.
Try to simply ignore such garbage output.
=> Update opens used for readlines.
